config/routes.rb
Rails.application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, only: [:create, :destroy]  

  root :to => 'pages#home'
  match '/register', :to => 'users#new', via: 'get'
  match '/login', :to => 'sessions#new', via: 'get'
  match '/logout', :to => 'sessions#destroy', via: 'delete'
  match '/contact', :to => 'pages#contact', via: 'get'
  match '/about', :to => 'pages#about', via: 'get'
  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form <%= object.class.to_s.downcase %> contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <div class="feed-items">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </div>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
  <div class="post">
    <div class="post-content">
      <div class="post-block">
        <div class="post-img-link">
          <%= link_to gravatar_for(feed_item.user, size: 55), feed_item.user, class: "block-img-link" %>
        </div>
      </div>
      <strong class="info-user-link">
        <%= link_to feed_item.user.name, feed_item.user %>
      </strong>
      <small class="info-post-time">
        - <%= post_time(feed_item.created_at) %>
      </small>
      <span class="content-delete">
        <% if current_user?(feed_item.user) %>
           <%= link_to "Delete", feed_item, method: :delete,
           data: { confirm: "You sure?" }, title: "Delete" %>
        <% end %>
      </span>
      <div class="content-text">
        <%= feed_item.content_html %>
      </div> 
    </div>   
  </div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>
   <%= content_tag(:div, value, class: "alert-#{key}") %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
   <div class="post-create">
     <div class="post-field">
       <%= f.text_area :content, placeholder: "Write post...", class: "text-area" %>
     </div>
     <div class="post-actions">
       <%= f.submit "Create post", class: "post-button" %>
     </div>
   </div>
   <div class="success">
     <%= render 'shared/flash_messages' %>
   </div>
   <div class="eror">
     <%= render 'shared/error_messages', :object => f.object %>
   </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <ul class="stats-list">
     <li class="stat">
         <a class="stat-link" title="<%= @user.microposts.count %> Posts" href="#">
             <span class="stat-label">POSTS</span></br>
             <span class="stat-value"><%= @user.microposts.count %></span>
         </a>
     </li>
     <li class="stat">     
         <a class="stat-link" title="<%= @user.followed_users.count %> Following" href="<%= following_user_path(@user) %>">
             <span class="stat-label">FOLLOWING</span></br>
             <span class="stat-value"><%= @user.followed_users.count %></span>
         </a>
     </li>
     <li class="stat"> 
         <a class="stat-link" title="<%= @user.followers.count %> Followers" href="<%= followers_user_path(@user) %>">
             <span class="stat-label">FOLLOWERS</span></br>
             <span class="stat-value" id="followers"><%= @user.followers.count %></span>
         </a>
     </li>
  </ul> 
</div>

app/views/shared/_success_messages.html.erb
<% flash.each do |key, value| %>
   <%= content_tag(:div, value, class: "alert-#{key}") %>
<% end %>

app/views/shared/_user_info.html.erb
<a class="user-block-link" href="<%= user_path(current_user) %>">
</a>
<div class="user-content">
  <a class="avatar-link" title="<%= current_user.name %>" href="<%= user_path(current_user) %>">
    <%= gravatar_for(current_user, size: 110) %>
  </a>
  <div class="user-fields">
    <div class="user-name">
      <%= link_to current_user.name, current_user,class: "user-name-link" %>
    </div>
    <span class="user-edit-link">
      <%= link_to "Edit Profile", edit_user_path(current_user), class: "user-edit" %>
    </span>
  </div>
  <%= render 'shared/stats' %>
</div>
   