config/routes.rb
Rails.application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, only: [:create, :destroy]  

  root :to => 'pages#home'
  match '/register', :to => 'users#new', via: 'get'
  match '/login', :to => 'sessions#new', via: 'get'
  match '/logout', :to => 'sessions#destroy', via: 'delete'
  match '/contact', :to => 'pages#contact', via: 'get'
  match '/about', :to => 'pages#about', via: 'get'
  

end

app/views/layouts/_footer.html.erb
<footer>
   <nav class="round">
     <ul>
       <li><%= link_to "About", "#" %></li>
       <li><%= link_to "Contact", "#" %></li>
     </ul>
   </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav>
       <ul>
           <li><%= link_to "Home", root_path, title: "Home" %></li>
           <% if loged_in? %>
             <li><%= link_to "Users", users_path, title: "Users" %></li>
             <li><%= link_to "Profile", user_path(current_user), title: "Profile" %></li>
             <li><%= link_to "Settings", edit_user_path(current_user), title: "Settings" %></li>
             <li><%= link_to "Logout", logout_path, method: "delete", title: "Logout" %></li>
           <% else %>
             <li><%= link_to "Register", register_path, title: "Register" %></li>
             <li><%= link_to "Login", login_path, title: "Login" %></li>
           <% end %>
       </ul>
    </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag    "application", media: "all",
                                            "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/stylesheets' %>
    <link rel="shortcut icon" href="http://www.iconj.com/ico/0/0/00tolq47s9.ico" type="image/x-icon" />
  </head>
  <body>
      <div class="header-cont">
        <%= render 'layouts/header' %>
      </div>
      <div class="container">
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>